language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

jdk:
  - oraclejdk8

before_script:
  # Kotlin binding staleness check.
  - ./gradlew generateKotlin
  - if [ ! -z "$(git status --porcelain)" ]; then echo "Bindings changed. Did you run 'generateKotlin'?"; exit 1; fi
  # Create and start an emulator for instrumentation tests.
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew ":$MODULE:build" ":$MODULE-kotlin:build" ":$MODULE:connectedCheck"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  matrix:
    - MODULE=rxbinding
    - MODULE=rxbinding-appcompat-v7
    - MODULE=rxbinding-design
    - MODULE=rxbinding-leanback-v17
    - MODULE=rxbinding-recyclerview-v7
    - MODULE=rxbinding-support-v4
  global:
    - secure: "kgsT0j2b0GYbQjrDSdIYoh9lXOb2bAqA8gOx7ipegYLiNUuAjTeclw/3IFd5WpPNEhwTvDlb8Pwi/GYsXwYLdjysZUsj73a027swKAuXRBEjnBpfcvhEwKdoO5Ygoz/uH7TvcuCKzEz/bRKIglvn9PcTrzIHHZZIXa/mLU5otNE="
    - secure: "XNvNiKfh2+JAHvbj7/jtaHKcu5FlN0fHwKwiDZYiCkTkG4kXsKlGtbQX4uk/RU4ZEe3pCPt1I6u66e5c57SLiDNMI0dnjdmSWL6Pcd1CoJVagYYq48TNgQARRe1zntXZvweRmqbfnsQiX5neLwaDj+UNM1yq6D3h2quPVrgoBBM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
